/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.Conexao;
import DAO.DAOTitulos;
import MODEL.Locadora;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.LineBorder;

/**
 *
 * @author ALUNO
 */
public class IncluirTitulo extends javax.swing.JPanel {
    Locadora loc = new Locadora();
    
    int cod;
    /**
     * Creates new form IncluirTitulo
     */
    String res;
    String res1;
    String s;
    int num;
    Conexao con = new Conexao();
    DAOTitulos title = new DAOTitulos();
        public IncluirTitulo() {
        initComponents();
        title.executeSQL("SELECT codigo FROM db_locadora.tb_titulos");
        try
        {
            title.resultado.last();
            res =  (title.resultado.getString("codigo"));
            num =Integer.parseInt(res);
            num= num +1;
            System.out.println(res);
            System.out.println(num);
            s = Integer.toString(num);
            codigo.setText("0"+s);
             //title.resultado.getInt("codigo");
             
        }catch(SQLException ex) {
            Logger.getLogger(IncluirTitulo.class.getName()).log(Level.SEVERE, null, ex);
    }
         title.executeSQL("SELECT codigo,nome FROM db_locadora.tb_titulos");
        try
        {
            title.resultado.last();
            res =  (title.resultado.getString("nome"));
            res1 = (title.resultado.getString("codigo"));
            System.out.println(res);
            ultimo.setText("0"+res1+" - "+res);
             //title.resultado.getInt("codigo");
             
        }catch(SQLException ex) {
            Logger.getLogger(IncluirTitulo.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NomeTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AnoTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Midia = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        Atores = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Audio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Legendas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Classificacao = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Descricao = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        SalvarDados = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        novo = new javax.swing.JButton();
        genero = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        ultimo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Codigo:");

        codigo.setEditable(false);
        codigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codigo.setEnabled(false);
        codigo.setMinimumSize(new java.awt.Dimension(6, 29));
        codigo.setPreferredSize(new java.awt.Dimension(6, 29));
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        NomeTitulo.setForeground(new java.awt.Color(153, 153, 153));
        NomeTitulo.setText("Digite o nome do título");
        NomeTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeTituloActionPerformed(evt);
            }
        });
        NomeTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NomeTituloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NomeTituloFocusLost(evt);
            }
        });

        jLabel3.setText("Ano:");

        AnoTitulo.setForeground(new java.awt.Color(153, 153, 153));
        AnoTitulo.setText("AAAA");
        AnoTitulo.setMaximumSize(new java.awt.Dimension(4, 4));
        AnoTitulo.setMinimumSize(new java.awt.Dimension(4, 4));
        AnoTitulo.setPreferredSize(new java.awt.Dimension(34, 29));
        AnoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnoTituloActionPerformed(evt);
            }
        });
        AnoTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AnoTituloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AnoTituloFocusLost(evt);
            }
        });

        jLabel4.setText("Genero:");

        jLabel5.setText("Midia (s):");

        Midia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "DVD", "Blue ray", "DVD e Blue ray" }));

        jLabel6.setText("Atores:");

        Atores.setForeground(new java.awt.Color(153, 153, 153));
        Atores.setText("Digite o nome dos principais atores, separados por vírgulas.");
        Atores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtoresActionPerformed(evt);
            }
        });
        Atores.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AtoresFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AtoresFocusLost(evt);
            }
        });

        jLabel7.setText("Audio (s):");

        Audio.setForeground(new java.awt.Color(153, 153, 153));
        Audio.setText("Informe as faixas de audio contida no título separado por vírgulas.");
        Audio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AudioActionPerformed(evt);
            }
        });
        Audio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AudioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AudioFocusLost(evt);
            }
        });

        jLabel8.setText("Legendas:");

        Legendas.setForeground(new java.awt.Color(153, 153, 153));
        Legendas.setText("Informe as legendas contidas no título, separe-as com vírgulas.");
        Legendas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LegendasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LegendasFocusLost(evt);
            }
        });

        jLabel9.setText("Classificação:");

        Classificacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Livre", "Maiores de 16", "Mariores de 18" }));

        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("*");

        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jLabel18.setText("*");

        jLabel19.setForeground(new java.awt.Color(255, 51, 51));
        jLabel19.setText("*");

        jLabel20.setForeground(new java.awt.Color(255, 51, 51));
        jLabel20.setText("*");

        jLabel21.setForeground(new java.awt.Color(255, 51, 51));
        jLabel21.setText("*");

        jLabel22.setForeground(new java.awt.Color(255, 51, 51));
        jLabel22.setText("*");

        jLabel23.setForeground(new java.awt.Color(255, 51, 51));
        jLabel23.setText("*");

        Descricao.setColumns(20);
        Descricao.setForeground(new java.awt.Color(153, 153, 153));
        Descricao.setRows(5);
        Descricao.setText("Digite a descrição do filme, enredo etc.");
        Descricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DescricaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DescricaoFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(Descricao);

        jLabel10.setText("Sinopse:");

        SalvarDados.setText("Salvar");
        SalvarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarDadosActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        status.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        status.setText("Bem vindo (a) !!!");

        jLabel24.setForeground(new java.awt.Color(255, 51, 51));
        jLabel24.setText("*");

        novo.setText("Novo");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });

        genero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selcione", "Ação", "Comédia", "Romance", "Suspense", "Terror", "Documentário", "Infantil", "Adulto 18+", "Nacionais", "Ficção Científica" }));
        genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoActionPerformed(evt);
            }
        });

        jLabel11.setText("Ultimo cadastro:");

        ultimo.setEditable(false);
        ultimo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ultimo.setEnabled(false);
        ultimo.setMinimumSize(new java.awt.Dimension(6, 29));
        ultimo.setPreferredSize(new java.awt.Dimension(6, 29));
        ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(AnoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(Classificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(novo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SalvarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Legendas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Audio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                            .addComponent(Atores, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeTitulo)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ultimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)))
                                .addGap(18, 18, 18)
                                .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(Midia, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11)
                    .addComponent(ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(NomeTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(Midia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Atores, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Audio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Legendas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AnoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Classificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalvarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(novo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NomeTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeTituloActionPerformed
      
    }//GEN-LAST:event_NomeTituloActionPerformed

    private void AnoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnoTituloActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_AnoTituloActionPerformed

    private void SalvarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarDadosActionPerformed
        
       /* String titulo = NomeTitulo.getText();
        title.executeSQL("SELECT nome FROM db_locadora.tb_titulos");
        try
        {
            title.resultado.first();
            do
            {
            res =  (title.resultado.getString("nome"));
            System.out.println(res);
            if(res.equals(titulo))
            {
                NomeTitulo.setText("Esse titulo já foi cadastrado!!");
                NomeTitulo.setForeground(Color.red);
                NomeTitulo.setBorder(new LineBorder(Color.red));
            }
            }while(title.resultado.next());
             
        }catch(SQLException ex) {
            Logger.getLogger(IncluirTitulo.class.getName()).log(Level.SEVERE, null, ex);
    }*/
        
        
        if(NomeTitulo.getText().equals("Digite o nome do título")
           && AnoTitulo.getText().equals("AAAA")
           && Atores.getText().equals("Digite o nome dos principais atores, separados por vírgulas.")
           && Audio.getText().equals("Informe as faixas de audio contida no título separado por vírgulas.")
           && Legendas.getText().equals("Informe as legendas contidas no título, separe-as com vírgulas."))
        {
            NomeTitulo.setBorder(new LineBorder(Color.red));
            NomeTitulo.setText("Digite o nome do título");
            NomeTitulo.setForeground(Color.gray);
            
            AnoTitulo.setBorder(new LineBorder(Color.red));
            AnoTitulo.setText("AAAA");
            AnoTitulo.setForeground(Color.gray);
            
            Atores.setBorder(new LineBorder(Color.red));
            Atores.setText("Digite o nome dos principais atores, separados por vírgulas.");
            Atores.setForeground(Color.gray);
            
            Audio.setBorder(new LineBorder(Color.red));
            Audio.setText("Informe as faixas de audio contida no título separado por vírgulas.");
            Audio.setForeground(Color.gray);
            
            Legendas.setBorder(new LineBorder(Color.red));
            Legendas.setText("Informe as legendas contidas no título, separe-as com vírgulas.");
            Legendas.setForeground(Color.gray);
            
            genero.setForeground(Color.red);
            status.setText("Verifique os campos obrigatórios");
            status.setForeground(Color.red);
            genero.setBorder(new LineBorder(Color.red));
        }else if
           (AnoTitulo.getText().equals("AAAA")
           && Atores.getText().equals("Digite o nome dos principais atores, separados por vírgulas.")
           && Audio.getText().equals("Informe as faixas de audio contida no título separado por vírgulas.")
           && Legendas.getText().equals("Informe as legendas contidas no título, separe-as com vírgulas."))
        {
                        
            AnoTitulo.setBorder(new LineBorder(Color.red));
            AnoTitulo.setText("AAAA");
            AnoTitulo.setForeground(Color.gray);
            
            Atores.setBorder(new LineBorder(Color.red));
            Atores.setText("Digite o nome dos principais atores, separados por vírgulas.");
            Atores.setForeground(Color.gray);
            
            Audio.setBorder(new LineBorder(Color.red));
            Audio.setText("Informe as faixas de audio contida no título separado por vírgulas.");
            Audio.setForeground(Color.gray);
            
            Legendas.setBorder(new LineBorder(Color.red));
            Legendas.setText("Informe as legendas contidas no título, separe-as com vírgulas.");
            Legendas.setForeground(Color.gray);
            
            status.setText("Verifique os campos obrigatórios");
            status.setForeground(Color.red);
        }
        else if
           (Atores.getText().equals("Digite o nome dos principais atores, separados por vírgulas.")
           && Audio.getText().equals("Informe as faixas de audio contida no título separado por vírgulas.")
           && Legendas.getText().equals("Informe as legendas contidas no título, separe-as com vírgulas."))
        {
                       
            Atores.setBorder(new LineBorder(Color.red));
            Atores.setText("Digite o nome dos principais atores, separados por vírgulas.");
            Atores.setForeground(Color.gray);
            
            Audio.setBorder(new LineBorder(Color.red));
            Audio.setText("Informe as faixas de audio contida no título separado por vírgulas.");
            Audio.setForeground(Color.gray);
            
            Legendas.setBorder(new LineBorder(Color.red));
            Legendas.setText("Informe as legendas contidas no título, separe-as com vírgulas.");
            Legendas.setForeground(Color.gray);
            
            status.setText("Verifique os campos obrigatórios");
            status.setForeground(Color.red);
        }
        
        else  if(NomeTitulo.getText().equals("Digite o nome do título"))
        {
            NomeTitulo.setBorder(new LineBorder(Color.red));
            NomeTitulo.setText("Digite o nome do título");
            NomeTitulo.setForeground(Color.gray);
            
            status.setText("Verifique os campos obrigatórios");
            status.setForeground(Color.red);
        }
        else if (AnoTitulo.getText().equals("AAAA"))
        {
            AnoTitulo.setBorder(new LineBorder(Color.red));
            AnoTitulo.setText("AAAA");
            AnoTitulo.setForeground(Color.gray);
            
            status.setText("Verifique os campos obrigatórios");
            status.setForeground(Color.red);
        }
        else if (Atores.getText().equals("Digite o nome dos principais atores, separados por vírgulas."))
        {
            Atores.setBorder(new LineBorder(Color.red));
            Atores.setText("Digite o nome dos principais atores, separados por vírgulas.");
            Atores.setForeground(Color.gray);
            
            status.setText("Verifique os campos obrigatórios");
            status.setForeground(Color.red);
        }
        else if(Audio.getText().equals("Informe as faixas de audio contida no título separado por vírgulas."))
        {
            Audio.setBorder(new LineBorder(Color.red));
            Audio.setText("Informe as faixas de audio contida no título separado por vírgulas.");
            Audio.setForeground(Color.gray);
           
            status.setText("Verifique os campos obrigatórios");
            status.setForeground(Color.red);
        }
        else if (Legendas.getText().equals("Informe as legendas contidas no título, separe-as com vírgulas."))
        {
            Legendas.setBorder(new LineBorder(Color.red));
            Legendas.setText("Informe as legendas contidas no título, separe-as com vírgulas.");
            Legendas.setForeground(Color.gray);
            
            status.setText("Verifique os campos obrigatórios");
            status.setForeground(Color.red);
        }
        else
        {
        this.cod=Integer.parseInt(codigo.getText());
        loc.incluirTitulos(cod,genero.getSelectedItem().toString(),NomeTitulo.getText(),AnoTitulo.getText(),Midia.getSelectedItem().toString(),Atores.getText(),Audio.getText(),Legendas.getText(),Classificacao.getSelectedItem().toString(),Descricao.getText());
        status.setText("Status: salvo com sucesso!!");
        status.setForeground(Color.green);
        
        title.executeSQL("SELECT codigo FROM db_locadora.tb_titulos");
        try
        {
            title.resultado.last();
            res =  (title.resultado.getString("codigo"));
            num =Integer.parseInt(res);
            num= num +1;
            System.out.println(res);
            System.out.println(num);
            s = Integer.toString(num);
            codigo.setText("0"+s);
             //title.resultado.getInt("codigo");
             
        }catch(SQLException ex) {
            Logger.getLogger(IncluirTitulo.class.getName()).log(Level.SEVERE, null, ex);
    }
         title.executeSQL("SELECT codigo,nome FROM db_locadora.tb_titulos");
        try
        {
            title.resultado.last();
            res =  (title.resultado.getString("nome"));
            res1 = (title.resultado.getString("codigo"));
            System.out.println(res);
            ultimo.setText("0"+res1+" - "+res);
             //title.resultado.getInt("codigo");
             
        }catch(SQLException ex) {
            Logger.getLogger(IncluirTitulo.class.getName()).log(Level.SEVERE, null, ex);
    }
        NomeTitulo.setText("Digite o nome do título");
        NomeTitulo.setForeground(Color.gray);
        AnoTitulo.setText("AAAA");
        AnoTitulo.setForeground(Color.gray);
        Audio.setText("Informe as faixas de audio contida no título separado por vírgulas.");
        Audio.setForeground(Color.gray);
        Atores.setText("Digite o nome dos principais atores, separados por vírgulas.");
        Atores.setForeground(Color.gray);
        Legendas.setText("Informe as legendas contidas no título, separe-as com vírgulas.");
        Legendas.setForeground(Color.gray);
        Descricao.setText("Digite a descrição do filme, enredo etc.");
        Descricao.setForeground(Color.gray);
        genero.setSelectedIndex(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarDadosActionPerformed

    private void NomeTituloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NomeTituloFocusGained
        // TODO add your handling code here:

        if(NomeTitulo.getText().equals("Digite o nome do título") || NomeTitulo.getText().equals("O Titulo já foi cadastrado!!"))
        {
            NomeTitulo.setForeground(Color.BLACK);
            NomeTitulo.setText("");
            NomeTitulo.setBorder(new LineBorder(Color.LIGHT_GRAY));
            status.setText("Preenchendo");
            status.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_NomeTituloFocusGained

    private void NomeTituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NomeTituloFocusLost
        String titulo = NomeTitulo.getText();
        title.executeSQL("SELECT nome FROM db_locadora.tb_titulos");
        try
        {
            title.resultado.first();
            do
            {
            res =  (title.resultado.getString("nome"));
            System.out.println(res);
            if(res.equalsIgnoreCase(titulo))
            {
                NomeTitulo.setText("O Titulo já foi cadastrado!!");
                NomeTitulo.setForeground(Color.red);
                NomeTitulo.setBorder(new LineBorder(Color.red));
            }
            }while(title.resultado.next());
             
        }catch(SQLException ex) {
            Logger.getLogger(IncluirTitulo.class.getName()).log(Level.SEVERE, null, ex);
    }
        if(NomeTitulo.getText().equals(""))
        {
            NomeTitulo.setText("Digite o nome do título");
            NomeTitulo.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_NomeTituloFocusLost

    private void AtoresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AtoresFocusGained
        if(Atores.getText().equals("Digite o nome dos principais atores, separados por vírgulas."))
        {
            Atores.setText("");
            Atores.setForeground(Color.black);
            Atores.setBorder(new LineBorder(Color.LIGHT_GRAY));
            status.setText("Preenchendo");
            status.setForeground(Color.black);
        }
    }//GEN-LAST:event_AtoresFocusGained

    private void AudioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AudioFocusLost
        if(Audio.getText().equals(""))
        {
            Audio.setText("Informe as faixas de audio contida no título separado por vírgulas.");
            Audio.setForeground(Color.gray);
            
        }
    }//GEN-LAST:event_AudioFocusLost

    private void AtoresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AtoresFocusLost
        if(Atores.getText().equals(""))
        {
            Atores.setText("Digite o nome dos principais atores, separados por vírgulas.");
            Atores.setForeground(Color.gray);
        }
    }//GEN-LAST:event_AtoresFocusLost

    private void AnoTituloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AnoTituloFocusGained
        if(AnoTitulo.getText().equals("AAAA"))
        {
            AnoTitulo.setText("");
            AnoTitulo.setForeground(Color.BLACK);
            AnoTitulo.setBorder(new LineBorder(Color.LIGHT_GRAY));
            status.setText("Preenchendo");
            status.setForeground(Color.black);
        }
    }//GEN-LAST:event_AnoTituloFocusGained

    private void AnoTituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AnoTituloFocusLost
       if(AnoTitulo.getText().equals(""))
       {
           AnoTitulo.setText("AAAA");
           AnoTitulo.setForeground(Color.gray);
       }
    }//GEN-LAST:event_AnoTituloFocusLost

    private void AudioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AudioFocusGained
        if(Audio.getText().equals("Informe as faixas de audio contida no título separado por vírgulas."))
        {
            Audio.setText("");
            Audio.setForeground(Color.BLACK);
            Audio.setBorder(new LineBorder(Color.LIGHT_GRAY));
            status.setText("Preenchendo");
            status.setForeground(Color.black);
        }
    }//GEN-LAST:event_AudioFocusGained

    private void AudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AudioActionPerformed

    private void LegendasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LegendasFocusGained
        if(Legendas.getText().equals("Informe as legendas contidas no título, separe-as com vírgulas."))
        {
            Legendas.setText("");
            Legendas.setForeground(Color.BLACK);
            Legendas.setBorder(new LineBorder(Color.LIGHT_GRAY));
            status.setText("Preenchendo");
            status.setForeground(Color.black);
        }
    }//GEN-LAST:event_LegendasFocusGained

    private void LegendasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LegendasFocusLost
        if(Legendas.getText().equals(""))
        {
            Legendas.setText("Informe as legendas contidas no título, separe-as com vírgulas.");
            Legendas.setForeground(Color.gray);
        }
    }//GEN-LAST:event_LegendasFocusLost

    private void DescricaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DescricaoFocusGained
       if(Descricao.getText().equals("Digite a descrição do filme, enredo etc."))
       {
           Descricao.setText("");
           Descricao.setForeground(Color.BLACK);
           Descricao.setBorder(new LineBorder(Color.LIGHT_GRAY));
           status.setText("Preenchendo");
            status.setForeground(Color.black);
       }
    }//GEN-LAST:event_DescricaoFocusGained

    private void DescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DescricaoFocusLost
        if(Descricao.getText().equals(""))
        {
            Descricao.setText("Digite a descrição do filme, enredo etc.");
            Descricao.setForeground(Color.gray);
        }
    }//GEN-LAST:event_DescricaoFocusLost

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        
       
    }//GEN-LAST:event_CancelarActionPerformed

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        
        title.executeSQL("SELECT codigo FROM db_locadora.tb_titulos");
        try
        {
            title.resultado.last();
            res =  (title.resultado.getString("codigo"));
            num =Integer.parseInt(res);
            num= num +1;
            System.out.println(res);
            System.out.println(num);
            s = Integer.toString(num);
            codigo.setText("0"+s);
             //title.resultado.getInt("codigo");
             
        }catch(SQLException ex) {
            Logger.getLogger(IncluirTitulo.class.getName()).log(Level.SEVERE, null, ex);
    }
        NomeTitulo.setText("Digite o nome do título");
        NomeTitulo.setForeground(Color.gray);
        AnoTitulo.setText("AAAA");
        AnoTitulo.setForeground(Color.gray);
        Audio.setText("Informe as faixas de audio contida no título separado por vírgulas.");
        Audio.setForeground(Color.gray);
        Atores.setText("Digite o nome dos principais atores, separados por vírgulas.");
        Atores.setForeground(Color.gray);
        Legendas.setText("Informe as legendas contidas no título, separe-as com vírgulas.");
        Legendas.setForeground(Color.gray);
        Descricao.setText("Digite a descrição do filme, enredo etc.");
        Descricao.setForeground(Color.gray);
        genero.setSelectedIndex(0);
    }//GEN-LAST:event_novoActionPerformed

    private void AtoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AtoresActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    private void generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoActionPerformed
       
    }//GEN-LAST:event_generoActionPerformed

    private void ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ultimoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnoTitulo;
    private javax.swing.JTextField Atores;
    private javax.swing.JTextField Audio;
    private javax.swing.JButton Cancelar;
    private javax.swing.JComboBox Classificacao;
    private javax.swing.JTextArea Descricao;
    private javax.swing.JTextField Legendas;
    private javax.swing.JComboBox Midia;
    private javax.swing.JTextField NomeTitulo;
    private javax.swing.JButton SalvarDados;
    private javax.swing.JTextField codigo;
    private javax.swing.JComboBox genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton novo;
    private javax.swing.JLabel status;
    private javax.swing.JTextField ultimo;
    // End of variables declaration//GEN-END:variables
}
